### ISSUE TITLE
Repeated commands silently crash CAN interface when disconnected

### ISSUE THREAD

**Issue by BenjaminPelletier** [PolySync/oscc-joystick-commander#9] opened 2017-08-30 15:56 UTC
With the Leaf USB-CAN device connected to the computer (and can0 enabled) but not the OSCC controller, run joystick commander and then hold down the Back button for a couple seconds.  Many "Disable controls" messages will scroll by (see issue #8) and then the program just exits with exit code 0 (no error).  After this happens, the can0 interface is still present in ifconfig, but there is an error when trying to open it via running joystick commander again.  This condition can be reset by unplugging and replugging the Leaf and then re-enabling can0.

Expected behavior is, at a minimum, for some error state to be indicated via error message (preferably), or via exit code at bare minimum.

**Comment by vertexmachina** [comment] 2017-09-06 18:11
> With the Leaf USB-CAN device connected to the computer (and can0 enabled) but not the OSCC controller

Do mean that you have the Leaf connected to your PC and can0 is configured and present in `ifconfig`, but the Leaf is not connected to the Control CAN bus of the OSCC modules?

**Comment by BenjaminPelletier** [comment] 2017-09-06 18:13
Yes, exactly.  Everything ready to go except that the DB9 connection between the Leaf and OSCC controller is disconnected.

**Comment by vertexmachina** [comment] 2017-09-07 20:13
The problem is that the TX buffer becomes full when there is no receiving device on the other end. 

Unfortunately it seems the only way to clear the buffer is a down-up of the CAN interface, which is why unplugging and replugging the Kvaser followed by the `ip link` commands fixes it.

We'll be adding a message to the API that will tell you when and why a socket `write()` fails so it is no longer silent, but that will be in the `oscc` repo rather than this one, so I'll close this issue.

**Closed as completed by vertexmachina** 2017-09-07 20:13 UTC
